project:
  type: website
  output-dir: docs

website:
  title: "186 - Gestión de Datos"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/yabellini/gestiondedatos
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: clase1.qmd
        text: Clase 1 - Introducción
      - href: clase2.qmd
        text: Clase 2 - Modelos de datos
      - href: clase3.qmd
        text: Clase 3 - Diseño de Bases de Datos
      - href: clase4.qmd
        text: Clase 4 - Diseño de Bases de Datos
      - href: clase5.qmd
        text: Clase 5 - SQL
      - href: clase6.qmd
        text: Clase 6 - SQL
      - href: clase7.qmd
        text: Clase 7 - SQL
      - href: clase8.qmd
        text: Clase 8 - SQL y R
      - href: clase9.qmd
        text: Clase 9 -  R
      - href: clase10.qmd
        text: Clase 10 - SQL
      - href: ejerciciosextra.qmd
        text: Guía de Ejercicios
      - href: evaluaciones.qmd
        text: Parciales y Finales
format:
  html:
    theme: sandstone
    # css: styles.css
    toc: true

execute:
  freeze: auto

